/**
 * Every catalogue id ever published, in the order it was published.
 *
 * **Append-only.** Nothing is ever removed from this list and nothing in it is
 * ever edited: sets on people's devices point at these ids, including sets
 * logged offline that have not reached the server yet. `catalogue.test.ts` fails
 * if any id here stops resolving in `CATALOGUE` — which is what makes "retire,
 * never delete" a rule the suite enforces rather than one somebody remembers.
 *
 * Adding an exercise means adding its id here too; the same test fails for a
 * catalogue id that was never registered, so an addition is always deliberate.
 */
export const PUBLISHED_IDS: readonly string[] = [
  'ex-goblet-squat',
  'ex-leg-press',
  'ex-barbell-back-squat',
  'ex-barbell-front-squat',
  'ex-hack-squat',
  'ex-zercher-squat',
  'ex-box-squat',
  'ex-smith-machine-squat',
  'ex-romanian-deadlift',
  'ex-conventional-deadlift',
  'ex-trap-bar-deadlift',
  'ex-hip-thrust',
  'ex-good-morning',
  'ex-back-extension',
  'ex-kettlebell-swing',
  'ex-single-leg-rdl',
  'ex-cable-pull-through',
  'ex-walking-lunge',
  'ex-reverse-lunge',
  'ex-bulgarian-split-squat',
  'ex-step-up',
  'ex-split-squat',
  'ex-curtsy-lunge',
  'ex-lateral-lunge',
  'ex-db-bench-press',
  'ex-barbell-bench-press',
  'ex-overhead-press',
  'ex-db-shoulder-press',
  'ex-incline-db-press',
  'ex-push-up',
  'ex-dip',
  'ex-machine-chest-press',
  'ex-landmine-press',
  'ex-lat-pulldown',
  'ex-pull-up',
  'ex-chin-up',
  'ex-seated-cable-row',
  'ex-barbell-row',
  'ex-db-row',
  'ex-chest-supported-row',
  'ex-face-pull',
  'ex-inverted-row',
  'ex-pallof-press',
  'ex-cable-woodchop',
  'ex-landmine-rotation',
  'ex-half-kneeling-chop',
  'ex-russian-twist',
  'ex-bird-dog',
  'ex-dead-bug',
  'ex-side-plank',
  'ex-farmer-s-carry',
  'ex-suitcase-carry',
  'ex-front-rack-carry',
  'ex-overhead-carry',
  'ex-sled-push',
  'ex-sled-drag',
  'ex-waiter-s-walk',
  'ex-lateral-raise',
  'ex-cable-curl',
  'ex-db-curl',
  'ex-hammer-curl',
  'ex-tricep-pushdown',
  'ex-overhead-tricep-extension',
  'ex-leg-extension',
  'ex-leg-curl',
  'ex-calf-raise',
  'ex-cable-abduction',
  'ex-glute-kickback',
  'ex-rear-delt-fly',
  'ex-chest-fly',
];
