-- Backfills descriptions and photographs onto accounts that already existed
-- when those columns were added.
--
-- 0004 added the columns with empty defaults, and nothing would ever fill
-- them: seedNewUser runs once at sign-up, and sync only re-sends a row whose
-- seq moved, which adding a column does not do. Without this, every account
-- created before today would show blank detail sheets forever.
--
-- `seq` is bumped deliberately so the change actually reaches devices, and
-- `updated_at` with it so last-write-wins does not discard it.
--
-- Written by hand rather than generated: drizzle-kit diffs schema, not data.
-- Guarded on description = '' so a description the user has edited is never
-- overwritten by a later redeploy.

UPDATE exercises SET description = 'Hold one weight at your chest and sit straight down between your knees. The weight up front keeps your chest tall, which is why it is the easiest squat to learn.', images = '["/exercises/goblet-squat/0.jpg","/exercises/goblet-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Goblet Squat' AND description = '';
UPDATE exercises SET description = 'Push the platform away through your whole foot. Stop lowering when your lower back starts to lift off the pad.', images = '["/exercises/leg-press/0.jpg","/exercises/leg-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Leg Press' AND description = '';
UPDATE exercises SET description = 'Bar across your upper back, sit down and slightly back, drive up through mid-foot. The heaviest way most people can train the squat.', images = '["/exercises/barbell-back-squat/0.jpg","/exercises/barbell-back-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Barbell Back Squat' AND description = '';
UPDATE exercises SET description = 'Bar resting on the front of your shoulders, elbows high. It punishes any forward lean, so it keeps you upright and honest.', images = '["/exercises/barbell-front-squat/0.jpg","/exercises/barbell-front-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Barbell Front Squat' AND description = '';
UPDATE exercises SET description = 'A squat on a machine with your back supported, so your legs give out before your torso does.', images = '["/exercises/hack-squat/0.jpg","/exercises/hack-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Hack Squat' AND description = '';
UPDATE exercises SET description = 'Bar held in the crooks of your elbows. Uncomfortable, but very hard to do with a rounded back.', images = '["/exercises/zercher-squat/0.jpg","/exercises/zercher-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Zercher Squat' AND description = '';
UPDATE exercises SET description = 'Squat down to a box, pause, then stand. The pause removes the bounce and teaches you to sit back.', images = '["/exercises/box-squat/0.jpg","/exercises/box-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Box Squat' AND description = '';
UPDATE exercises SET description = 'A squat on a fixed bar path. Useful when you train alone and want to push close to failure safely.', images = '["/exercises/smith-machine-squat/0.jpg","/exercises/smith-machine-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Smith Machine Squat' AND description = '';
UPDATE exercises SET description = 'Push your hips back with a soft knee and let the bar travel down your thighs. Stop when your hamstrings run out of stretch, not when the weight reaches the floor.', images = '["/exercises/romanian-deadlift/0.jpg","/exercises/romanian-deadlift/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Romanian Deadlift' AND description = '';
UPDATE exercises SET description = 'Pull the bar from the floor with your hips and shoulders rising together. The biggest test of the hinge there is.', images = '["/exercises/conventional-deadlift/0.jpg","/exercises/conventional-deadlift/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Conventional Deadlift' AND description = '';
UPDATE exercises SET description = 'Deadlift standing inside the bar with the handles at your sides. Easier on the lower back than a straight bar.', images = '["/exercises/trap-bar-deadlift/0.jpg","/exercises/trap-bar-deadlift/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Trap Bar Deadlift' AND description = '';
UPDATE exercises SET description = 'Shoulders on a bench, drive your hips up until your body makes a straight line. Squeeze at the top rather than arching your back.', images = '["/exercises/hip-thrust/0.jpg","/exercises/hip-thrust/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Hip Thrust' AND description = '';
UPDATE exercises SET description = 'Bar on your back, hinge forward with a flat back, then stand. Small weights go a long way here.', images = '["/exercises/good-morning/0.jpg","/exercises/good-morning/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Good Morning' AND description = '';
UPDATE exercises SET description = 'Hinge over the pad and raise your torso to straight — no further. A hinge you can do for higher reps without much load.', images = '["/exercises/back-extension/0.jpg","/exercises/back-extension/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Back Extension' AND description = '';
UPDATE exercises SET description = 'Snap your hips forward to throw the bell up to chest height. It is a hinge, not a squat, and your arms are only rope.', images = '["/exercises/kettlebell-swing/0.jpg","/exercises/kettlebell-swing/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Kettlebell Swing' AND description = '';
UPDATE exercises SET description = 'Hinge over one leg with the other reaching back as a counterweight. It exposes the left-to-right imbalance a two-leg hinge hides.', images = '["/exercises/single-leg-rdl/0.jpg","/exercises/single-leg-rdl/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Single-Leg RDL' AND description = '';
UPDATE exercises SET description = 'Face away from the cable and drive your hips forward against it. Teaches the hinge with no load on your spine at all.', images = '["/exercises/cable-pull-through/0.jpg","/exercises/cable-pull-through/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Cable Pull-Through' AND description = '';
UPDATE exercises SET description = 'Step forward, drop the back knee towards the floor, then step through. Keep the front shin roughly upright.', images = '["/exercises/walking-lunge/0.jpg","/exercises/walking-lunge/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Walking Lunge' AND description = '';
UPDATE exercises SET description = 'Step backwards into the lunge rather than forwards. Kinder to the knees and much easier to balance.', images = '["/exercises/reverse-lunge/0.jpg","/exercises/reverse-lunge/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Reverse Lunge' AND description = '';
UPDATE exercises SET description = 'Back foot on a bench, drop straight down on the front leg. Brutal for how little weight it needs.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Bulgarian Split Squat' AND description = '';
UPDATE exercises SET description = 'Step onto a box and stand up through the top leg, without pushing off the floor with the trailing one.', images = '["/exercises/step-up/0.jpg","/exercises/step-up/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Step-Up' AND description = '';
UPDATE exercises SET description = 'Feet split front and back, drop straight down and back up. Learn this before the Bulgarian version.', images = '["/exercises/split-squat/0.jpg","/exercises/split-squat/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Split Squat' AND description = '';
UPDATE exercises SET description = 'Step one leg behind and across the other. It reaches the side of the hip that straight-ahead lunges miss.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Curtsy Lunge' AND description = '';
UPDATE exercises SET description = 'Step wide to one side and sit into that hip, keeping the other leg straight. The only lunge that trains sideways.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Lateral Lunge' AND description = '';
UPDATE exercises SET description = 'Press two dumbbells from your chest. The free path lets your shoulders find a position a bar forces on them.', images = '["/exercises/db-bench-press/0.jpg","/exercises/db-bench-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'DB Bench Press' AND description = '';
UPDATE exercises SET description = 'Lower the bar to your chest under control and press it back up. Keep your shoulder blades pulled together throughout.', images = '["/exercises/barbell-bench-press/0.jpg","/exercises/barbell-bench-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Barbell Bench Press' AND description = '';
UPDATE exercises SET description = 'Press the bar from your shoulders to overhead, finishing with it over your ears. Squeeze your glutes so you press rather than lean back.', images = '["/exercises/overhead-press/0.jpg","/exercises/overhead-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Overhead Press' AND description = '';
UPDATE exercises SET description = 'Press two dumbbells overhead. Easier on the shoulders than a bar for most people.', images = '["/exercises/db-shoulder-press/0.jpg","/exercises/db-shoulder-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'DB Shoulder Press' AND description = '';
UPDATE exercises SET description = 'Bench set at about thirty degrees, which shifts the work to the upper chest and front of the shoulder.', images = '["/exercises/incline-db-press/0.jpg","/exercises/incline-db-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Incline DB Press' AND description = '';
UPDATE exercises SET description = 'Whole body in one line, lower your chest to just off the floor. Ribs down — it is the hips sagging that ruins it.', images = '["/exercises/push-up/0.jpg","/exercises/push-up/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Push-Up' AND description = '';
UPDATE exercises SET description = 'Lower between the bars until your upper arms are about parallel, then press up. Lean forward for chest, stay upright for triceps.', images = '["/exercises/dip/0.jpg","/exercises/dip/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Dip' AND description = '';
UPDATE exercises SET description = 'A chest press on a fixed path. Good for pushing hard when you are tired or training alone.', images = '["/exercises/machine-chest-press/0.jpg","/exercises/machine-chest-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Machine Chest Press' AND description = '';
UPDATE exercises SET description = 'Press a bar anchored at one end up and slightly forward. The middle ground between flat and overhead pressing.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Landmine Press' AND description = '';
UPDATE exercises SET description = 'Pull the bar to your collarbone and let your elbows drive down. The pull-up, but loadable to the kilo.', images = '["/exercises/lat-pulldown/0.jpg","/exercises/lat-pulldown/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Lat Pulldown' AND description = '';
UPDATE exercises SET description = 'Hang with palms forward and pull your chest towards the bar. Start every rep from a dead hang.', images = '["/exercises/pull-up/0.jpg","/exercises/pull-up/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Pull-Up' AND description = '';
UPDATE exercises SET description = 'Palms facing you. Slightly easier than a pull-up, and considerably more biceps.', images = '["/exercises/chin-up/0.jpg","/exercises/chin-up/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Chin-Up' AND description = '';
UPDATE exercises SET description = 'Pull the handle to your stomach and let your shoulder blades travel back. Stop your torso rocking to move the weight.', images = '["/exercises/seated-cable-row/0.jpg","/exercises/seated-cable-row/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Seated Cable Row' AND description = '';
UPDATE exercises SET description = 'Hinge over and row the bar to your stomach. Back flat, torso still.', images = '["/exercises/barbell-row/0.jpg","/exercises/barbell-row/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Barbell Row' AND description = '';
UPDATE exercises SET description = 'One hand supported, row the dumbbell to your hip. Pull with your back rather than just your arm.', images = '["/exercises/db-row/0.jpg","/exercises/db-row/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'DB Row' AND description = '';
UPDATE exercises SET description = 'Row lying face down on an incline bench. It takes your lower back out of the movement entirely.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Chest-Supported Row' AND description = '';
UPDATE exercises SET description = 'Pull a rope towards your face with your elbows high. The best small fix for shoulders rounded by pressing.', images = '["/exercises/face-pull/0.jpg","/exercises/face-pull/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Face Pull' AND description = '';
UPDATE exercises SET description = 'Bar at hip height, body straight, pull your chest to the bar. A row that needs no weights at all.', images = '["/exercises/inverted-row/0.jpg","/exercises/inverted-row/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Inverted Row' AND description = '';
UPDATE exercises SET description = 'Press a cable straight out in front while it tries to twist you. You are training not to rotate.', images = '["/exercises/pallof-press/0.jpg","/exercises/pallof-press/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Pallof Press' AND description = '';
UPDATE exercises SET description = 'Rotate and pull the cable diagonally across your body. Turn through your ribs, not your lower back.', images = '["/exercises/cable-woodchop/0.jpg","/exercises/cable-woodchop/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Cable Woodchop' AND description = '';
UPDATE exercises SET description = 'Swing the end of the bar side to side in an arc. Keep your hips fairly still so your trunk does the work.', images = '["/exercises/landmine-rotation/0.jpg","/exercises/landmine-rotation/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Landmine Rotation' AND description = '';
UPDATE exercises SET description = 'Chop the cable across your body from one knee. Kneeling takes the legs away so the trunk cannot cheat.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Half-Kneeling Chop' AND description = '';
UPDATE exercises SET description = 'Sit leaning back and rotate side to side under control. Speed does nothing here.', images = '["/exercises/russian-twist/0.jpg","/exercises/russian-twist/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Russian Twist' AND description = '';
UPDATE exercises SET description = 'On hands and knees, extend the opposite arm and leg without letting your hips tilt. Harder and more useful than it looks.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Bird Dog' AND description = '';
UPDATE exercises SET description = 'On your back, lower the opposite arm and leg while your lower back stays flat on the floor.', images = '["/exercises/dead-bug/0.jpg","/exercises/dead-bug/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Dead Bug' AND description = '';
UPDATE exercises SET description = 'On one forearm, body straight from head to heels. It trains the side of your trunk, which almost nothing else does.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Side Plank' AND description = '';
UPDATE exercises SET description = 'Carry a heavy weight in each hand and walk. The simplest exercise here and one of the hardest to finish.', images = '["/exercises/farmer-s-carry/0.jpg","/exercises/farmer-s-carry/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Farmer''s Carry' AND description = '';
UPDATE exercises SET description = 'Walk with one weight locked out overhead, arm by your ear. Start far lighter than you expect to need.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Waiter''s Walk' AND description = '';
UPDATE exercises SET description = 'Carry one weight at your side and walk without leaning. The whole exercise is refusing to tip.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Suitcase Carry' AND description = '';
UPDATE exercises SET description = 'Carry the weight at your shoulders and walk tall. Very demanding on the upper back — and on breathing.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Front Rack Carry' AND description = '';
UPDATE exercises SET description = 'Walk with the weight locked out overhead. Ruthless about shoulder position and ribs staying down.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Overhead Carry' AND description = '';
UPDATE exercises SET description = 'Drive a loaded sled forward with short, hard steps. All effort, almost no soreness the next day.', images = '["/exercises/sled-push/0.jpg","/exercises/sled-push/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Sled Push' AND description = '';
UPDATE exercises SET description = 'Walk forward pulling a sled behind you. A carry your grip will not cut short.', images = '["/exercises/sled-drag/0.jpg","/exercises/sled-drag/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Sled Drag' AND description = '';
UPDATE exercises SET description = 'Raise the weights out to the sides to shoulder height. Light weight, and no swinging.', images = '["/exercises/lateral-raise/0.jpg","/exercises/lateral-raise/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Lateral Raise' AND description = '';
UPDATE exercises SET description = 'Curl against a cable, so the biceps stay loaded through the whole range rather than just the middle.', images = '["/exercises/cable-curl/0.jpg","/exercises/cable-curl/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Cable Curl' AND description = '';
UPDATE exercises SET description = 'Curl two dumbbells with your elbows staying at your sides.', images = '["/exercises/db-curl/0.jpg","/exercises/db-curl/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'DB Curl' AND description = '';
UPDATE exercises SET description = 'Curl with your palms facing each other. Hits the forearm and the outside of the upper arm.', images = '["/exercises/hammer-curl/0.jpg","/exercises/hammer-curl/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Hammer Curl' AND description = '';
UPDATE exercises SET description = 'Push the cable down by straightening your elbows, upper arms pinned to your sides.', images = '["/exercises/tricep-pushdown/0.jpg","/exercises/tricep-pushdown/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Tricep Pushdown' AND description = '';
UPDATE exercises SET description = 'Lower the weight behind your head and straighten your arms. The stretched position is the part that matters.', images = '["/exercises/overhead-tricep-extension/0.jpg","/exercises/overhead-tricep-extension/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Overhead Tricep Extension' AND description = '';
UPDATE exercises SET description = 'Straighten your knees against the pad. Isolates the quads and asks nothing of anything else.', images = '["/exercises/leg-extension/0.jpg","/exercises/leg-extension/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Leg Extension' AND description = '';
UPDATE exercises SET description = 'Bend your knees against the pad. The hamstring work that hinging on its own does not cover.', images = '["/exercises/leg-curl/0.jpg","/exercises/leg-curl/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Leg Curl' AND description = '';
UPDATE exercises SET description = 'Rise onto your toes through a full range and lower slowly. Calves want reps and a real stretch.', images = '["/exercises/calf-raise/0.jpg","/exercises/calf-raise/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Calf Raise' AND description = '';
UPDATE exercises SET description = 'Take one leg out to the side against a cable. Small muscles, but the ones that keep your hips level when you walk.', images = '[]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Cable Abduction' AND description = '';
UPDATE exercises SET description = 'Drive one leg back against a cable and squeeze at the end. Do not arch your back to get further.', images = '["/exercises/glute-kickback/0.jpg","/exercises/glute-kickback/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Glute Kickback' AND description = '';
UPDATE exercises SET description = 'Pull the weights out and back with arms almost straight. The back of the shoulder, which pressing never reaches.', images = '["/exercises/rear-delt-fly/0.jpg","/exercises/rear-delt-fly/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Rear Delt Fly' AND description = '';
UPDATE exercises SET description = 'Open your arms wide with a slight bend at the elbow, then bring them back together. Chase the stretch, not the weight.', images = '["/exercises/chest-fly/0.jpg","/exercises/chest-fly/1.jpg"]'::jsonb, seq = nextval('change_seq'), updated_at = now() WHERE name = 'Chest Fly' AND description = '';
