/**
 * Writing the demo account's history to the database.
 *
 * An empty account demonstrates nothing: the coverage grid has no ticks, the
 * progress charts have no line, the strength score has nothing to divide, and
 * "ready for more weight" — the thing that makes the app worth using — cannot
 * appear at all, because it needs history to derive a verdict from. So the demo
 * account arrives having already trained.
 *
 * What it arrives with is generated by `demo-history`, which is pure and holds
 * every judgement about what plausible training looks like. This file only
 * turns those data points into rows: it reads the plan back out of the
 * database, asks for sets, and inserts them. Keeping the two apart is what lets
 * the interesting half be tested without Postgres.
 */

import { sql } from 'drizzle-orm';
import { db } from '@/lib/db';
import {
  bodyLogs,
  exercises as exercisesTable,
  patterns,
  programEntries,
  setLogs,
} from '@/lib/db/schema';
import { mondayOf } from '@athletic/domain';
import { demoHistory, type DemoPlanEntry } from './demo-history';
import { nextSeq, seedId } from './seed-user';

/**
 * Which address gets this treatment.
 *
 * Read at call time from the environment rather than frozen at import, so a
 * test can point it somewhere harmless. A constant would force the test to
 * create — and then delete — the real demo account, on whatever database it
 * happened to be pointed at.
 */
export const demoEmail = (): string =>
  (process.env.DEMO_EMAIL ?? 'demo-gymmy@yopmail.com').trim().toLowerCase();

export const isDemoEmail = (email?: string | null): boolean =>
  (email ?? '').trim().toLowerCase() === demoEmail();

/**
 * Fills an account that already has the default library with training history.
 *
 * Reads the program back out of the database rather than regenerating it, so
 * the logs point at the exercises this account was actually given — inventing a
 * parallel plan here is how a demo ends up with progress charts for lifts that
 * are not in its own week.
 */
export async function seedDemoHistory(userId: string): Promise<void> {
  const [plan, library, patternRows] = await Promise.all([
    db
      .select()
      .from(programEntries)
      .where(sql`${programEntries.userId} = ${userId}`),
    db
      .select()
      .from(exercisesTable)
      .where(sql`${exercisesTable.userId} = ${userId}`),
    db
      .select()
      .from(patterns)
      .where(sql`${patterns.userId} = ${userId}`),
  ]);
  if (!plan.length) return;

  const keyByPattern = new Map(patternRows.map((p) => [p.id, p.key]));
  /** Exercise → what it is called and what it trains, which is what decides a
   *  sane weight. A deadlift and a lateral raise have nothing in common. */
  const byId = new Map(
    library.map((e) => [e.id, { name: e.name, patternKey: keyByPattern.get(e.patternId) ?? null }]),
  );

  const entries: DemoPlanEntry[] = plan.flatMap((p) => {
    const exercise = p.exerciseId ? byId.get(p.exerciseId) : null;
    if (!p.exerciseId || !exercise) return [];
    return [
      {
        sessionIndex: p.sessionIndex,
        exerciseId: p.exerciseId,
        name: exercise.name,
        patternKey: exercise.patternKey,
        sets: p.sets,
      },
    ];
  });

  const { sets, weights } = demoHistory(entries, mondayOf(new Date()));

  const rows: (typeof setLogs.$inferInsert)[] = sets.map((s) => ({
    // Derived, not random, for the same reason the rest of the seed is: this
    // has to be safe to run again over a history it half wrote.
    id: seedId(userId, 'demoLog', `${s.date}:${s.exerciseId}:${s.setNo}`),
    userId,
    updatedAt: new Date(`${s.date}T18:00:00Z`),
    deletedAt: null,
    seq: 0,
    date: s.date,
    session: s.session,
    exerciseId: s.exerciseId,
    setNo: s.setNo,
    weight: s.weight,
    reps: s.reps,
    rir: s.rir,
    note: '',
  }));

  // Chunked: a single statement with thousands of parameters trips Postgres's
  // limit, and this is the one place that inserts in bulk.
  for (let i = 0; i < rows.length; i += 200) {
    const chunk = rows.slice(i, i + 200).map((r) => ({ ...r, seq: nextSeq }));
    await db.insert(setLogs).values(chunk).onConflictDoNothing();
  }

  await db
    .insert(bodyLogs)
    .values(
      weights.map((b) => ({
        id: seedId(userId, 'demoWeight', b.date),
        userId,
        updatedAt: new Date(`${b.date}T07:00:00Z`),
        deletedAt: null,
        seq: nextSeq,
        date: b.date,
        weight: b.weight,
        note: '',
      })),
    )
    .onConflictDoNothing();
}
